server:
  port: 5000
## Oauth2 Client
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 8e6b9c93ea66d0012a20
            client-secret: c95e4592b520dfc245f82f3e2fabc8455a402d20
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user

        provider:
          github:
            authorization-uri: http://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user


---
  jpa:
    database: mysql
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  # DataSource
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.rassword}